### ISSUE TITLE
Error compiling the project

### ISSUE THREAD

**Issue by atontini** [kushagra10025/OpenGL-Starter#2]
I have tried to compile the project and i got this error:
`/usr/bin/ld: cannot find -lopengl32: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/OpenGLStarter.dir/build.make:101: OpenGLStarter] Error 1
make[1]: *** [CMakeFiles/Makefile2:136: CMakeFiles/OpenGLStarter.dir/all] Error 2
make: *** [Makefile:136: all] Error 2`

I am using Fedora 39 and i have installed OpenGL 4.6, am i missing something?

**Comment by kushagra10025** [comment]
Hi,
Can you try with GL in the CMakeLists instead of opengl32, that was windows specific. If you are still finding it difficult to proceed or want a fresh perspective on how to approach this you can contact me on discord - negprot

Thanks

**Comment by atontini** [comment]
> Hi, Can you try with GL in the CMakeLists instead of opengl32, that was windows specific. If you are still finding it difficult to proceed or want a fresh perspective on how to approach this you can contact me on discord - negprot
> 
> Thanks

Thank you too, I have added you so we can chat
